### ISSUE TITLE
System Document

### ISSUE THREAD

**Issue by matthewjflee** [Vezorla/vezorla-backend#186]
# System Document
General issue parent issue for the system document deliverable

- [x] System overview #175 
- [x] System deployment #176 
- [x] Deficiency list #177 
- [x] Sequence Diagrams #174 
- [x] State Machine Diagram #178 
- [x] Class Diagrams #179 
- [x] Package Diagram #180 
- [x] ERD #184 
- [x] Acceptance Test Plan #181 
- [x] Legacy Document #182 
- [x] Attribution Document #183 
- [x] User Manual #185 
- [x] Javadoc #191 
- [x] Revise use case descriptions #187 
- [x] System Administration #194
