### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by matthewjflee** [Vezorla/vezorla-backend#36]
# Capstone Roadmap 

Just a general issue to show the roadmap of what we need to do for back-end

## Customer
- [x] UC 20: Join mailing list
- [x] UC 21: Contact business
- [x] UC 22: View all products
- [x] UC 23: View product
- [x] UC 24: Add product to cart
- [x] UC 25: View Cart - Customer
- [x] UC 26: Change product quantity in cart - Customer
- [x] UC 27: Place order - Customer
- [x] UC 28: Apply discount - Customer

## Client
- [x] UC 14: Login
- [x] UC 15: Logout
- [x] UC 16: View order history - Client
- [x] UC 17: View invoice - Client
- [x] UC 18: Update account - Client
- [x] UC 19: Create account
- [x] UC 24: Add product to cart - Client
- [x] UC 25: View Cart - Client
- [x] UC 26: Change product quantity in cart - Client
- [x] UC 27: Place order - Client
- [x] UC 28: Apply discount - Client
- [x] UC 29: Forgot password

## Admin
- [x] UC 01: View inventory
- [x] UC 02: Create product
- [x] UC 03: Update product
- [x] UC 04: Create warehouse
- [ ] UC 05: Generate Report
- [x] UC 06: Export data
- [x] UC 07: Create PO
- [ ] UC 08: Review business order
- [ ] UC 09: Decline business order
- [ ] UC 10: Accept business order
- [ ] UC 11: Create business account
- [x] UC 12: Restore backup
- [x] UC 13: Create discount
- [x] UC 16: View order history - Admin
- [x] UC 17: View invoice - Admin
- [x] UC 18: Update account - Admin

**Comment by matthewjflee** [comment]
Good job @jjrr1717 we are finished!!!!!
